config/routes.rb
Rails.application.routes.draw do
  resources :instructions
  resources :ingredients
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy, inverse_of: :recipe
    accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank

    has_many :instructions, dependent: :destroy, inverse_of: :recipe
    accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :amount, :unit, :sub_heading)
    end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_instruction, only: %i[ show edit update destroy ]

  # GET /instructions or /instructions.json
  def index
    @instructions = Instruction.all
  end

  # GET /instructions/1 or /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    @instruction = Instruction.new
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions or /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to instruction_url(@instruction), notice: "Instruction was successfully created." }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1 or /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to instruction_url(@instruction), notice: "Instruction was successfully updated." }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1 or /instructions/1.json
  def destroy
    @instruction.destroy

    respond_to do |format|
      format.html { redirect_to instructions_url, notice: "Instruction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instruction_params
      params.require(:instruction).permit(:description, :sub_step)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.instructions.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :duration, :servings, :description, ingredients_attributes: %i[
        name, amount, unit, sub_heading, :_destroy
      ], instructions_attributes: %i[
        description, sub_step, :_destroy
      ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Recipe App Les goooo</h1>
<p> Dis the landing page
- Maybe add recently added recipes?
</p>
<%= link_to "Recipes", recipes_path %>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :sub_heading, style: "display: block" %>
    <%= form.text_field :sub_heading %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= ingredient.amount %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= ingredient.unit %>
  </p>

  <p>
    <strong>Sub heading:</strong>
    <%= ingredient.sub_heading %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>

app/views/instructions/_form.html.erb
<%= form_with(model: instruction) do |form| %>
  <% if instruction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
        <% instruction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :sub_step, style: "display: block" %>
    <%= form.text_field :sub_step %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instructions/_instruction.html.erb
<div id="<%= dom_id instruction %>">
  <p>
    <strong>Description:</strong>
    <%= instruction.description %>
  </p>

  <p>
    <strong>Sub step:</strong>
    <%= instruction.sub_step %>
  </p>

</div>

app/views/instructions/edit.html.erb
<h1>Editing instruction</h1>

<%= render "form", instruction: @instruction %>

<br>

<div>
  <%= link_to "Show this instruction", @instruction %> |
  <%= link_to "Back to instructions", instructions_path %>
</div>

app/views/instructions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Instructions</h1>

<div id="instructions">
  <% @instructions.each do |instruction| %>
    <%= render instruction %>
    <p>
      <%= link_to "Show this instruction", instruction %>
    </p>
  <% end %>
</div>

<%= link_to "New instruction", new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New instruction</h1>

<%= render "form", instruction: @instruction %>

<br>

<div>
  <%= link_to "Back to instructions", instructions_path %>
</div>

app/views/instructions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instruction %>

<div>
  <%= link_to "Edit this instruction", edit_instruction_path(@instruction) %> |
  <%= link_to "Back to instructions", instructions_path %>

  <%= button_to "Destroy this instruction", @instruction, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, data: {
  controller: "nested-form",
  nested_form_wrapper_selector_value: '.nested-form-wrapper'
}) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.text_field :duration %>
  </div>

  <div>
    <%= form.label :servings, style: "display: block" %>
    <%= form.number_field :servings %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

<%# Custom Logic Start%>
<%# Ingredients%>
<template data-nested-form-target="template">
    <%= form.fields_for :ingredients, Ingredient.new, child_index: 'NEW_RECORD' do |ingredient_fields| %>
      <%= render "ingredient_form", f: ingredient_fields %>
    <% end %>
  </template>

  <%= form.fields_for :ingredients do |ingredient_fields| %>
    <%= render "ingredient_form", f: ingredient_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add ingredient</button>

<%# Instructions%>
<template data-nested-form-target="template">
    <%= form.fields_for :instructions, Instruction.new, child_index: 'NEW_RECORD' do |instruction_fields| %>
      <%= render "instruction_form", f: instruction_fields %>
    <% end %>
  </template>

  <%= form.fields_for :instructions do |instruction_fields| %>
    <%= render "instruction_form", f: instruction_fields %>
  <% end %>

  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add instruction</button>



<%# Custom Logic End%>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :amount %>
  <%= f.text_field :amount %>
  
  <%= f.label :unit %>
  <%= f.text_field :unit %>
  
  <%= f.label :sub_heading %>
  <%= f.text_field :sub_heading %>

  <button type="button" data-action="nested-form#remove">Remove ingredient</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/recipes/_instruction_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :sub_step %>
  <%= f.text_field :sub_step %>

  <button type="button" data-action="nested-form#remove">Remove instruction</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= recipe.duration %>
  </p>

  <p>
    <strong>Servings:</strong>
    <%= recipe.servings %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>